language: csharp
solution: Application.sln
install:
  - nuget restore Application.sln
  - nuget install NUnit.Runners -Version 3.6.0
  - nuget install NUnitForms.Framework -Version 1.3.1
  - nuget install System.Windows.Forms -Version 4.0.0.0
script:
  - xbuild /p:Configuration=Release Application.sln
  - mono ./NUnit.ConsoleRunner.3.6.0/tools/nunit3-console.exe ./App.Test/bin/Release/App.Test.dll