language: csharp
solution: Application.sln
install:
  - nuget restore Application.sln
  - nuget install NUnit.Runners -Version 3.6.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Application.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.6.0/tools/nunit3-console.exe ./App.Test/bin/Release/App.Test.dll