language: csharp
solution: Calculator.sln
install:
  - nuget restore Calculator.sln
  - nuget install NUnit.Runners -Version 3.6.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Calculator.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.6.0/tools/nunit3-console.exe ./Calculator.Test/bin/Release/Calculator.Test.dll